# Generated by Django 5.0 on 2023-12-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('account', models.IntegerField()),
                ('day', models.IntegerField(default=0)),
                ('sum', models.IntegerField(default=0)),
            ],
        ),
    ]
