# Generated by Django 5.0 on 2023-12-20 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_num',
        ),
        migrations.RemoveField(
            model_name='user',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bankname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fishbread',
        ),
        migrations.RemoveField(
            model_name='user',
            name='holder',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
