# Generated by Django 5.0 on 2023-12-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fishbread',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('foundation_id', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('day', models.IntegerField(default=0)),
            ],
        ),
    ]
