# Generated by Django 5.0 on 2023-12-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishbread', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishbread',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
