# Generated by Django 5.0 on 2023-12-18 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('fishbread', '0002_alter_fishbread_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fishbread',
            name='foundation_id',
        ),
        migrations.AddField(
            model_name='fishbread',
            name='fishbread_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fishbread',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
