# Generated by Django 5.0 on 2023-12-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishbread', '0004_fishbread_id_alter_fishbread_fishbread_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishbread',
            name='foundation_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
